[package]
name = "pac-server"
authors = ["rinkimekari", "belkarx", "Keyshin"]
license = "MIT"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2"
local-ip-address = "0.4.4"
